import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import axios from 'axios'
import { useState } from 'react'
import { FlexBox, Wrapper, Text, ImgPlaceholder } from '../styles/global'

export default function Home() {
  const [data, setData] = useState({});
  const [location, setLocation] = useState('');
  const [weather, setWeather] = useState();
  const [errorMessage, setErrorMessage] = useState('')

  const searchLocation = (event) => {
    if (event.key === "Enter"){
      axios.get(url)
      .then((response) => {
        console.clear()
        setData(response.data)
        console.log(response.data)
        setWeather(response.data.weather)
        setErrorMessage("")
      }) .catch(err => {
        console.log(err)
        setErrorMessage("Please enter another location")
        setData({})
        setWeather()
      })
      setLocation('')
    }
  }

  var apiKey = "f1c3aba9f416efdb16702d2866709e98";
  var lang = "en";
  var units = "metric";
  const url = `https://api.openweathermap.org/data/2.5/weather?q=${location}&units=${units}&appid=${apiKey}&lang=${lang}`

  return (
    <div>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}

      <main>
        {errorMessage}
        <input
        value = {location}
        onChange={event=> setLocation(event.target.value)}
        placeholder="Enter Location"
        onKeyDown={searchLocation}
        type="text"
        >
        </input>

        {
          weather && weather.map((w, index) =>{
            return(
              <Wrapper bgImage="/kenrick-mills-MF9Wy1NA55I-unsplash-2.jpg">

                  <FlexBox key={index} dir="column" width="100%" height="100%">
                    <FlexBox dir="column" margin="200px 0 0 0">
                      <Text color="white" fontSize="65px" fontWeight="bold">{data.name}</Text>
                        <FlexBox alignItems="flex-start">
                          <Text color="white" fontSize="90px" fontWeight="bold">{data.main.temp.toFixed()}°</Text>
                          <FlexBox margin="15px 0 12px 10px"><Text color="white" fontSize="30px">{w.main} </Text></FlexBox>
                        </FlexBox>
                    </FlexBox>
                    <FlexBox margin="100px 0 0 0" bgColor="rgba(227, 227, 227, 0.25)" border="rgba(227, 227, 227) solid 2px" height="130px" width="60%" minWidth="600px" borderRadius="30px" justifyContent="space-around">
                      <FlexBox dir="column">
                        <Text color="white" fontSize="65px" fontWeight="700">{data.main.feels_like.toFixed()}°C</Text> 
                        <Text color="white">Feels like</Text>
                      </FlexBox>
                      <FlexBox dir="column">
                        <Text color="white" fontSize="65px" fontWeight="700">{data.main.humidity}%</Text> 
                        <Text color="white">Humidity</Text>
                      </FlexBox>
                      <FlexBox dir="column">
                        <FlexBox>
                          <Text color="white" fontSize="65px" fontWeight="700">{data.main.pressure}</Text>
                          <Text fontSize="20px" margin="0 0 15px 0" color="white">hPa</Text>
                        </FlexBox>
                        <Text color="white">Pressure</Text>
                      </FlexBox>
                      <FlexBox dir="column">
                        <FlexBox>
                          <Text color="white" fontSize="65px" fontWeight="700">{data.wind.speed}</Text>
                          <Text fontSize="20px" margin="0 0 15px 0" color="white">MPH</Text>
                        </FlexBox>
                        <Text color="white">Wind</Text>
                      </FlexBox>
                      {/* <img src= "http://openweathermap.org/img/wn/${w.icon}@4x.png" /> */}
                    </FlexBox>
                  </FlexBox>
              </Wrapper>
            )
          })
        }
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}
